version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    links:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=password
